<?php
/**
* English file for plugin djg_core
*
* @package wolf
* @subpackage djg_core
*
* @generated by djg_i18n_generator WolfCMS plugin - Michał Uchnast <djgprv@gmail.com>
*
**/
return array(
/** index.php */ 
'[djg] Core' => '[djg] Core', 
'Core' => 'Core', 
/** models\Djgcore.php */ 
'click to show adress' => 'click to show adress', 
/** views\documentation.php */ 
'Documentation' => 'Documentation', 
);