<?php
/**
* English file for plugin djg_core
*
* @package wolf
* @subpackage djg_core
*
* @generated by djg_i18n_generator WolfCMS plugin - Michał Uchnast 
*
**/
return array(
/** index.php */ 
'[djg] Core' => '[Djg] Core',
'Core' => 'Core',
/** models\Djgcore.php */ 
'click to show adress' => 'kliknij, aby zobaczyć adres',
'click to show phone number' => 'kliknij, aby zobaczyć numer telefonu',
/** views\documentation.php */ 
'Documentation' => 'Dokumentacja',
);